database:
  type: SQLITE
  file: "database.db"

cleanup:
  enabled: true
  days: 30          # удалять логи старше 30 дней
  interval-minutes: 60  # проверка раз в 60 минут

watch-groups:
  - ag
  - vlastilin
  - owner

alert:
  min-blocks: 100000
