mysql:
  enabled: true
  host: "mysql-de-fra9.joinserver.xyz"
  port: 3306
  database: "s259153_FAWEDetector"
  user: "u259153_kdtHPFkEin"
  password: "cyZrRalQ=z=tWifYkzOIJBCn"
  useSSL: false

# ГРУППЫ, ЗА КОТОРЫМИ СЛЕДИМ
# можешь дописывать сколько угодно
watch-groups:
  - ag
  - vlastilin
  - owner

# Минимум блоков, после которого логируется
alert:
  min-blocks: 100000
